apiVersion: v1
kind: Secret
metadata:
  name: normacontrol-secrets
  namespace: normacontrol
type: Opaque
stringData:
  datasource-url: jdbc:postgresql://postgres:5432/normacontrol
  datasource-username: norma
  datasource-password: change-me
  jwt-secret: change-me-base64-secret
